In [ ]:
import pandas as pd

**[Creating a Table in pandas]**

Variable_name = pd.DataFrame(2D list)

In [ ]:
df = pd.DataFrame([[57, 120],[52, 130],[55, 115], [51, 140]])
df

    0    1
0  57  120
1  52  130
2  55  115
3  51  140

**Assign Column Names**

In [ ]:
df.columns = ['column1', 'column2']
df

   column1  column2
0       57      120
1       52      130
2       55      115
3       51      140

**Rename Column Names**

In [ ]:
df = df.rename(columns={'column1': 'width', 'column2': 'engine-size'})
df

   width  engine-size
0     57          120
1     52          130
2     55          115
3     51          140

Using the to_csv() method of a DataFrame, you can save the created table as a CSV file as follows:

In [ ]:
df.to_csv('car_test_data.csv', index = False)

To read the saved file, use pandas' `read_csv()` function to import the file and store it as a variable:

In [ ]:
df2 = pd.read_csv('car_test_data.csv')
df2

   width  engine-size
0     57          120
1     52          130
2     55          115
3     51          140

**0.4. Model Building and Evaluation**

To build a machine learning model, you will import the scikit-learn machine learning library.

**[Importing the LinearRegression class from scikit-learn's linear_model module]**

from sklearn.linear_model import LinearRegression

In [ ]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

With just these two lines, we have now created a linear regression model. In the second line, we instantiated the class we imported. This way, you can simply assign the instance to a variable using the class name, and creating a model instance becomes easy.

Now, we just need to train the model with the data to complete the predictive model. Here, we will use data related to car prices explained by linear regression. Let's begin by running the code block below.

In [ ]:
import pandas as pd
test_data = pd.DataFrame(
    [
        [65, 120, 12000],
        [70, 115, 15000],
        [66, 130, 13500],
        [64, 133, 12100],
        [67, 127, 14200],
    ],
    columns=["width", "engine-size", "price"],
)
test_data

   width  engine-size  price
0     65          120  12000
1     70          115  15000
2     66          130  13500
3     64          133  12100
4     67          127  14200

For Features we'll use "width" and "engine-size"

In [ ]:
x = test_data[['width', 'engine-size']]
x

   width  engine-size
0     65          120
1     70          115
2     66          130
3     64          133
4     67          127

For the Target we'll use "Price"

In [ ]:
t = test_data['price']
t

0    12000
1    15000
2    13500
3    12100
4    14200
Name: price, dtype: int64

In scikit learn we use fit() method to train

In [ ]:
model.fit(x, t)

LinearRegression()

Let’s check the estimated bias and how the estimated weights are derived. The estimated bias is stored in the attribute intercept_, and the weights are stored in the attribute coef_.

By putting variables inside a string using curly braces {} and placing f before the string, you can embed the variable values inside the string.

In [ ]:
print(f'Estimated bias: {model.intercept_}')
print(f'Estimated weights: {model.coef_}')

Estimated bias: -45289.90362964962
Estimated weights: [725.63271188  83.74313249]

**Interpretation**

From the expression above, we can now say: w₁ = 725.63271188, w₂ = 83.74313249, and b = -45289.90362964962. Therefore, we can interpret this as: “For every 1 unit increase in vehicle width, the predicted price increases by approximately 725.63.”

In linear regression, the method used to calculate the bias and weights is called least squares. This method minimizes the sum of squared differences between the actual target variable (true value) and the predicted value.

**【Linear Regression Formula】**
                                 $$
\hat{y}  = f(x) = w_1 x_1 + w_2 x_2 + \dots + w_m x_m + b
$$


In least squares, the following value is minimized:

$$
\sum_{i=1}^{n} \left( y_i - \hat{y}_i \right)^2
$$

n : the number of data points in the dataset.

yi : the actual value of the target variable for the i-th observation.

y^i :the predicted value for the i-th observation.

That concludes the supervised learning workflow for regression problem. Using an external library called scikit-learn, you can construct a machine learning prediction model in just three lines of code:

Import the machine learning library → from ... import ...
Create an instance of the model → model = LinearRegression()
Fit the model to the data → model.fit()
Level 0 content ends here. To wrap up, let’s try the following practical exercises as a review.

# 0.5. Practice Problems

**Q0-1.** Create a pandas DataFrame using the table below.

|  | column1 | column2 | Price |
|-----|------|------|--|
| 0 | 50 | 128   | 12000 |
| 1 | 65 | 147   | 13400 |

In [ ]:
import pandas as pd

# Define data using a dictionary
data = {
    'column1': [50, 65],
    'column2': [128, 147],
    'Price': [12000, 13400]
}

# Create DataFrame
df = pd.DataFrame(data)
df

   column1  column2  Price
0       50      128  12000
1       65      147  13400

**Q0-2.** Rename the columns: `column1` as `height` and `column2` as `horsepower`.

In [ ]:
# Rename columns using dictionary mapping
df = df.rename(columns={'column1': 'height', 'column2': 'horsepower'})
df

   height  horsepower  Price
0      50         128  12000
1      65         147  13400

**Q0-3.** Save the above table as a CSV file with an appropriate file name (e.g., `data.csv`).
Make sure the file has been saved.
Note: Use single quotes when writing string values.

In [ ]:
# Save DataFrame to CSV file without saving the index
df.to_csv('data.csv', index=False)